# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

# Stable options only (compatible with stable Rust)
edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Basic style options (stable)
use_field_init_shorthand = true
force_explicit_abi = true
merge_derives = true
reorder_imports = true
reorder_modules = true

# Length limits
max_width = 100

# Function formatting  
fn_params_layout = "Tall"

# Misc
remove_nested_parens = true
