name: Maintenance

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  dependency-check:
    name: Check Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-outdated
      run: cargo install cargo-outdated
    
    - name: Check for outdated dependencies
      run: cargo outdated --exit-code 1
      continue-on-error: true
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Security audit
      run: cargo audit
    
    - name: Install cargo-deny
      run: cargo install cargo-deny
    
    - name: Check licenses and advisories
      run: cargo deny check
      continue-on-error: true

  msrv-check:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MSRV (1.70.0)
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: 1.70.0
    
    - name: Test with MSRV
      run: cargo check --all-targets --all-features

  unused-deps:
    name: Check Unused Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
    
    - name: Install cargo-udeps
      run: cargo install cargo-udeps --locked
    
    - name: Check for unused dependencies
      run: cargo +nightly udeps --all-targets
